tags = {
        'int': {'tag': 257, 'lexeme': 'int', 'width': 4},
        'float': {'tag': 257, 'lexeme': 'float', 'width': 8},
        'char': {'tag': 257, 'lexeme': 'char', 'width': 1},
        'bool': {'tag': 257, 'lexeme': 'bool', 'width': 1},
        'while': {'tag': 275, 'lexeme': 'while'},
        'do': {'tag': 259, 'lexeme': 'do'},
        'break': {'tag': 258, 'lexeme': 'break'},
        'if': {'tag': 265, 'lexeme': 'if'},
        'else': {'tag': 260, 'lexeme': 'else'},
        'true': {'tag': 274, 'lexeme': 'true'},
        'false': {'tag': 262, 'lexeme': 'false'},
        'and': {'tag': 256, 'lexeme': '&&'},
        'or': {'tag': 271, 'lexeme': '||'},
        'eq': {'tag': '='},
        'le': {'tag': '<'},
        'bg': {'tag': '>'},
        'letters': {'tag': 264},
        'value': {'tag': 270},
        'onlyoperators': {'tag': 264},
        'multioperators': {'tag': 263}
}
